server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ead-course
    username: postgres
    password: postgres#12A

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        '[show_sql]': true
        
        
